services:
  cake-app:
    container_name: cake-app
    build: ./docker/php
    depends_on:
      - mysql-5-7
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - "./cms/:/var/www/html"

  mysql-5-7:
    container_name: mysql-5-7
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
